### ISSUE TITLE
云鹭科技首次原生云游戏创意分享会：干货满满 收获好评

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#10]
链接：https://mp.weixin.qq.com/s/kKs3rNMDiDhJm5h9b0mCYw

云概念在互联网界喊了好几年，终于轮到游戏了。7月15日，云河原生云游戏开发中心首次原生云游戏研发创意分享会在斗鱼直播平台进行。云鹭科技CEO温向东在直播中为大家剖析了目前游戏开发者遇到的困难，提出了入局云游戏产业来打破目前游戏研发困境的解决方法。在中国5G云游戏产业联盟的指导下成立的云河原生云游戏中心，将在“原生云游戏”的这条赛道上，扮演一个“推进者”的角色。

**Comment by ZakaryCode** [comment]
感谢贡献
