### ISSUE TITLE
【图形编程】使用贝塞尔样条算法生成穿过预定义点的平滑曲线

### ISSUE THREAD

**Issue by fff1024** [o2team/tech-weekly#100]
链接 https://exploringswift.com/blog/Drawing-Smooth-Cubic-Bezier-Curve-through-prescribed-points-using-Swift

在设计师作图时, 通常会先定义若干点, 然后生成一条穿过这些点的平滑曲线, 再进行细节刻画。这种根据预定义点生成平滑曲线的算法叫做贝塞尔样条算法,  它还应用在很多的场景, 比如数据可视化中的曲线图、数值分析中曲线拟合和手绘软件中画笔的线条等。

**Comment by ZakaryCode** [comment]
感谢贡献
