### ISSUE TITLE
AntV：可视化数据解决方案

### ISSUE THREAD

**Issue by lillian98** [o2team/tech-weekly#101]
官网: https://antv.vision/zh

AntV是蚂蚁金服数据可视化解决方案，其中最常被提及的G2是基于图形出发的可视化引擎，采用The grammar Of Graphics开发理念，以数据为驱动，支持高交互的方案。最新的4.0版本使用TS重写，相较于容易上手的eCharts（底层依赖轻量级的矢量图形库 ZRender），开发文档不够完善，因此对于数据可视化小白同学门槛较高，但在拓展性、创造性拥有更大优势。目前AntV还有系列产品包括：G6（专注于关系数据的可视化引擎，支持交互、分析、动画等等功能）、F2（专注于移动端的解决方案，支持H5）、L7（专注于地理空间数据的解决方案）。其扩展产品有G2Plot、Graphin、ChartCube。

**Comment by ZakaryCode** [comment]
感谢贡献
