### ISSUE TITLE
腾讯 Code Review 规范

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#102]
链接：https://mp.weixin.qq.com/s/OmwRA0HI7fZ4pvIOmxs9WA

代码，是设计理念落地的地方，是技术的呈现和根本。同学们可以在 review 过程中做到落地沟通，不再是空对空的讨论，可以在实际问题中产生思考的碰撞，互相学习，大家都掌握团队里积累出来最好的实践方式！

**Comment by ZakaryCode** [comment]
感谢贡献
