### ISSUE TITLE
【人工智能】GPT-3 袭来，前端又要失业？谈谈如何实现智能切图

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#103]
地址：https://zhuanlan.zhihu.com/p/188437243
曾经，智能切图项目 [pix2code](https://github.com/tonybeltramelli/pix2code) 横空出世，它支持导入设计稿直接生成代码，惊艳了整个前端届，就在大家惊呼前端要失业的时候，这个项目却完美演绎了出道即巅峰，从此再无更新，渐渐被人遗忘。最近 GTP-3 再一次挑战前端，似乎前端这个领域总是充满危机感。本文由百度 FEX 负责人吴多益撰写，他用强悍的学习能力告诉我们，前端er 无需焦虑，任何新技术的出现都应该成为一个合格工程师手中的利剑，学习它，掌握它，然后用它惊艳所有人。So,keep learning,keep growing!

**Comment by ZakaryCode** [comment]
感谢贡献
