### ISSUE TITLE
Next.js 10 正式发布：带来诸多新特性

### ISSUE THREAD

**Issue by jacoobwang** [o2team/tech-weekly#104]
原文链接：https://mp.weixin.qq.com/s/-XZVrLqYLTDvNHvE6genVw

10月27号 Next.js conf 大会上发布了全新的版本-Next.js 10，本次发布的特性主要聚焦于开发者体验的提升和用户体验的提升，还包含了诸多亮点：内置图片组件 Image Component : next/image，自动进行图片优化；国际化路由 Internationalized Routing，多语言支持，自动语言检测等，一起来快速了解下吧~

**Comment by ZakaryCode** [comment]
感谢贡献
