### ISSUE TITLE
Introducing the New JSX Transform

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#105]
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

React 17 中引入了新的 JSX 语法转换机制，好处除了书写 JSX 时不再需要提前引入 `React` 对象外，还做了一些性能优化和概念简化的工作。如 `key` 独立于其它 `props` 而单独传递，不建议在函数式组件中使用 `defaultProps` 等。文章介绍了相关背景和大致的改动内容，以及升级与兼容的方法。关于此改动的动机和实现细节，可以浏览此 [RFC](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#detailed-design)。

**Comment by ZakaryCode** [comment]
感谢贡献
