### ISSUE TITLE
【编译原理】eval5，基于TypeScript编写的JavaScript解释器

### ISSUE THREAD

**Issue by bplok20010** [o2team/tech-weekly#106]
Github: https://github.com/bplok20010/eval5

eval5是基于 TypeScript 编写的 JavaScript 解释器，支持完整 ES5 语法解析，支持浏览器、node.js、小程序等 JavaScript 运行环境。在各类小程序盛行的今天，用它突破小程序对eval/Function的禁用限制，让你的应用具备动态执行代码及远程脚本的能力。

**Comment by ZakaryCode** [comment]
感谢贡献
