### ISSUE TITLE
阿里前端智能化 2020 年中总结

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#107]
链接：https://mp.weixin.qq.com/s/YzbAPM0dxQTmkiEtrjhPNw

前端智能化方向的提出是为了给前端技术带来变革，借助 AI 和机器学习的能力拓展前端，那在推动这个目标的过程中，遇到哪些问题呢？阿里就前端智能化方向给出了 2020年的年中总结及思考。

**Comment by ZakaryCode** [comment]
感谢贡献
