### ISSUE TITLE
中文技术文档写作风格指南

### ISSUE THREAD

**Issue by hentaicracker** [o2team/tech-weekly#108]
链接：https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E5%85%83%E7%B4%A0/index.html

一个好的项目离不开好的文档，一篇好的技术文档离不开好的规范。这个指南为开发者提供了一个中文技术文档的写作规范以及建议，提高中文文档的可读性和专业性。热爱写文章同学的福音。

**Comment by ZakaryCode** [comment]
感谢贡献
