### ISSUE TITLE
sqlflow: 蚂蚁金服开源的基于sql的描述语言

### ISSUE THREAD

**Issue by booxood** [o2team/tech-weekly#11]
[sqlflow](https://github.com/sql-machine-learning/sqlflow) 是蚂蚁金服开源的一种基于sql的描述语言，用户可以基于sql的方式实现机器学习模型训练和预测。打通了数据训练过程中提数，模型打造，训练三个步骤的隔阂。能够大大提高炼丹的效率以及开发者的专注度。目前已支持MySQL、Oracle、Hive。
via. 天惠

**Comment by ZakaryCode** [comment]
感谢贡献
