### ISSUE TITLE
机器学习在静态代码分析中的应用

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#110]
原文链接：https://hackernoon.com/machine-learning-in-static-code-analysis-0t293w3p

现今，机器学习已经被深度应用在生活中各个领域，本文提出了一个有趣的观点：机器学习能否帮助软件开发者挖掘程序中的 Bug？答案是肯定的。作者首先介绍了行业内已知的基于机器学习的静态分析器，如 DeepCode、Infer（来自 Facebook）、SapFix、Embold、CodeGuru（来自 Amazon）等等。然后，作者以实现一个使用机器学习技术寻找代码缺陷的代码分析器为例，来说明机器学习在代码分析领域里的困难和局限性。通读全文，最大的收益是作者在结合机器学习技术与应用场景的分析思路，有利于丰富我们在 ML 技术上的想象空间。

**Comment by ZakaryCode** [comment]
感谢贡献
