### ISSUE TITLE
一个收录优质交互体验的网站导航器

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#111]
网站地址：https://sharkle.com/

这个网站会随机跳转到一些基于 CSS3、Canvas 和 WebGL 技术实现的、具有令人赞叹的界面呈现和交互体验的优秀网站，工作忙碌之余，不妨来体验下 Web 渲染技术的强大能力～

**Comment by ZakaryCode** [comment]
感谢贡献
