### ISSUE TITLE
前端异常监控系统的落地

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#114]
地址：https://zhuanlan.zhihu.com/p/26085642
文中阐述了前端异常监控的目的，以及市面上已有的脚本/解决方案，并从方案架构、SDK 组成、API 设计、日志上报策略以及可视化几个方面进行了详细的思路说明，有助于大家深入了解前端异常监控的整体组成。

**Comment by ZakaryCode** [comment]
感谢贡献
