### ISSUE TITLE
深入理解 Vue3 Reactivity API

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#115]
乍一看目录和开篇，会让人产生又是一篇 Vue3 响应式 API 的用法介绍。但继续深入，会发现文章环环相扣。如通过 effect 引出 watchEffect 的使用场景和实现思路、由 track、trigger 引出 ref 的实现。令人印象深刻的是 toRefs、自动脱 ref 等比较难以理解的用法，其实是出自我们平时使用拓展运算符时不经意间引出的问题场景。阅读本文，能让我们能对 Vue3 响应式的 API 用法、使用场景和部分实现思路产生一定的了解。

**Comment by lyxuncle** [comment]
链接：https://mp.weixin.qq.com/s/mnsI8MxBmhomttV0UXWSyg

**Comment by ZakaryCode** [comment]
感谢贡献
