### ISSUE TITLE
开源富文本编辑器技术的演进

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#116]
链接：https://mp.weixin.qq.com/s/Ui0qaMup-KWXiz3RBM14Kw

从 UEditor、CKEditor 开始，从技术角度讲述了富文本编辑器的演化进程，并将其分为了3个阶段，如果你正在富文本编辑器的坑内，非常推荐深入了解一下。

**Comment by ZakaryCode** [comment]
感谢贡献
