### ISSUE TITLE
【前端框架】Vue 3.0 Ref-sugar 提案真的是自寻死路吗？

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#117]
最近 Vue 3.0 的  ref-sugar 提案在社区引起了轩然大波，很多人都在对这个提案进行吐槽，指责 Vue 3.0 成了 JS 方言制造者，但是一个标杆型框架的 RFC 的提出，必然是经过作者深思熟虑后的产物，我们需要深入理解 RFC 之后才能更好地对提案发表意见，接下来就跟随 react-lite 的作者工业聚，冷静而审慎地对  ref-sugar 提案进行深度剖析。
文章地址：https://zhuanlan.zhihu.com/p/287842109

**Comment by ZakaryCode** [comment]
感谢贡献
