### ISSUE TITLE
Pipcook：前端开发者的机器学习工具箱

### ISSUE THREAD

**Issue by booxood** [o2team/tech-weekly#12]
Pipcook 发布了 1.0，是淘系技术部 FX Team 研发的一款面向前端开发者的机器学习工具箱，通过 Boa 提供了无缝使用 Python 生态的能力，解决了机器学习与 JavaScript 的物理距离，对前端开发者上手机器学习更友好。
via. 楚文

**Comment by ZakaryCode** [comment]
下次要记得，加一下原文链接哦～

**Comment by ZakaryCode** [comment]
感谢贡献

**Comment by booxood** [comment]
@ZakaryCode 😂 嗯嗯，漏了，下次注意。
