### ISSUE TITLE
Vue 3 RFC

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#13]
## [Vue 3 RFC](https://github.com/vuejs/rfcs)

在 2019 年初，Vue 团队开始采用了 RFC (Request for Comments) 机制，Vue 3 的所有重大特性更新都可以在这里看到。每份 RFC 有固定的模板，提出者必须列出草案的动机、设计细节、缺陷和兼容策略等，这不仅能让提出者认真思索方案的可行性和各种边界情况，还能让社区参与到新特性的讨论与设计中来。无论是开源项目还是内部的大型项目，相信一定能从 RFC 机制中获益。

**Comment by ZakaryCode** [comment]
感谢贡献
