### ISSUE TITLE
【图形编程】华人团队打造3D手环, 让VR告别手柄

### ISSUE THREAD

**Issue by fff-99** [o2team/tech-weekly#15]
链接[https://mp.weixin.qq.com/s/YnR00PO2JDSuTJ33Sg8Rhg](url)

最近,  康奈尔大学的华人教授带领国内本科生通过手环获得手指红外线成像结合深度神经网络, 以3D的形式对手指骨骼20多个关节进行了重建。该技术将在 VR、手语翻译、人机交互等方向有广泛的应用

**Comment by ZakaryCode** [comment]
感谢贡献
