### ISSUE TITLE
如何用 WebGL 构建 Github Globe

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#157]
链接：https://github.blog/2020-12-21-how-we-built-the-github-globe/

Github 前段时间更新了官网首页，其中 Globe 地球动效十分吸引人，本文将从技术的角度分析 Github 是如何使用 WebGL 构建实时地球动效的。

**Comment by ZakaryCode** [comment]
[开源世界的新“大门”](https://github.blog/2020-12-21-how-we-built-the-github-globe/)

**概要**：

> GitHub 是全世界构建软件的地方。全球有超过 5,600 万名开发人员在 GitHub 上构建和协作。透过全新主页，GitHub 团队向社区展示开源开发如何超越我们所生活的边界，并通过开发者的旅程来讲述的产品故事。

**推荐语**：

> GitHub 前段时间更新了官网首页，其中 Globe 地球动效十分吸引人，本文来自 GitHub 团队的博客，以技术角度分析如何使用 WebGL 构建实时地球动效的，其中很多细节的优化和思考，如创意与性能优化之间的平衡，感知速度、动效质量等等都值得细细揣摩。
