### ISSUE TITLE
从一个上天的项目看前端架构

### ISSUE THREAD

**Issue by hentaicracker** [o2team/tech-weekly#158]
链接：https://mp.weixin.qq.com/s/f7tzRE0cgQxCP6MNQW5SxQ

本文带你看看 SpaceX 上天的项目是如何开发的，并且通过学习该项目的一些开发规范和代码层次结构得出前端架构的一些思考。SpaceX 的火箭控制台是使用 JavaScript 开发的，”面试造火箭“这句话真的不假。

**Comment by ZakaryCode** [comment]
[SpaceX 上的前端架构](https://mp.weixin.qq.com/s/f7tzRE0cgQxCP6MNQW5SxQ)

**概要**：

> 本文带你看看 SpaceX 上天的项目是如何开发的，并且通过学习该项目的一些开发规范和代码层次结构得出前端架构的一些思考。SpaceX 的火箭控制台是使用 JavaScript 开发的，”**面试造火箭**“这句话真的不假。


**推荐语**：

> **前端没有架构？？？**
>
> 我们在很多时候都可以听到这样的暴论，但是这就是我们不得不接受的现实？恐怕也未必。那么作为前端架构师又应该为何负责那些内容，我们如何成为一名前端架构师？或许这哥“上天的项目”能给到一点点启发，让我们在这条成长的路上向前迈进。
