### ISSUE TITLE
【人工智能】可视化卷积神经网络解释器

### ISSUE THREAD

**Issue by kyjo2014** [o2team/tech-weekly#16]
【链接】https://poloclub.github.io/cnn-explainer/
CNN（卷积神经网络）是学习AI过程中必定会了解到的概念。但了解CNN的工作原理需要大量专业知识，小白使用的时候不得不把它当成一个黑箱处理。而佐治亚理工中国博士出品的可视化解释器，把CNN按步拆解并辅以图形解释通过点击CNN不同模块就能展示是怎么识别图片和物品的。

**Comment by ZakaryCode** [comment]
感谢贡献
