### ISSUE TITLE
谷歌发布首个线上 Web 开发者大会

### ISSUE THREAD

**Issue by chuyik** [o2team/tech-weekly#17]
链接 https://mp.weixin.qq.com/s/HJX3Vr7p-r_xsVzKWf1l3A

谷歌在本月初完成首次线上 Web 开发者大会 (web.dev/live)，以线上视频的形式，分享关于优化核心 Web 指标的最佳实践，Cookie 隐私和安全保护、构建工具与打包优化、Chrome DevTools 改进等技术干货。

**Comment by ZakaryCode** [comment]
感谢贡献
