### ISSUE TITLE
卫哲的3+1思考法：测量项目“靠谱程度”

### ISSUE THREAD

**Issue by xiaodi-112** [o2team/tech-weekly#171]
[思考产品“靠谱程度”](http://iamsujie.com/8000/8018/)

**概要**：

> 本文通过一些小案例详细介绍了“卫哲的3+1思考法”的内容：需求是从哪里来的，目标客户是谁？有多少人有这样的需求，这个需求紧迫吗？他们的痛是什么，场景是什么（用产品之前/之后）？解决之后在网站数据上会有什么表现？以及在现实场景中对评估项目的帮助。

**推荐语**：

> 都说要站在用户的鞋子里看问题，无论是产品还是项目，找到其背后的本质问题才能更好的规划和实现；“3+1”可以帮助产品同学理清思路，准确找到“用什么方法解决哪些人的什么问题“的答案，也可以帮助开发同学更好的理解需求，降低评估过程中的误差；文章和案例有些年头了，但是思想还是值得学习一下的，提供了一个思考问题的切入点。

**Comment by ZakaryCode** [comment]
推荐语和概要有点重复，期待可以有差异化的内容：
- 概要中主要描述在文章中的大纲和可能的收益
- 推荐语中倾向与表述内容本身对于读者的价值，为什么需要有这方面的了解，结合实际场景和自己的看法聊一聊
