### ISSUE TITLE
深入思考逻辑回归

### ISSUE THREAD

**Issue by hyechow** [o2team/tech-weekly#172]
[温故而知新---你真的掌握逻辑回归了吗？](https://shimo.im/docs/grDghhXcTHHtygTX)

**概要**：

> 这篇文章主要回顾了逻辑回归算法，并具体从数学角度去剖析算法背后的建模思路和实现逻辑。

**推荐语**：

> 逻辑回归是CTR预测场景上的常用模型，深入思考理解透彻其背后的逻辑和机理，不仅能使我知道如何去调优改进模型、也能带动我们以点带面的，让我们对机器学习的方法论有一个更全面更清晰的认知

**Comment by ZakaryCode** [comment]
推荐的标题可以更有吸引力一些，在概要中可以对文章的大纲详细讲一讲

推荐语更多的还是能和时事热点、具体的研发场景结合，而不是如此抽象

**Comment by ZakaryCode** [comment]
[用户推荐算法的敲门砖](https://shimo.im/docs/grDghhXcTHHtygTX)

**概要**：

> 逻辑回归是CTR预测场景上的常用模型，深入思考理解透彻其背后的逻辑和机理，不仅能使我知道如何去调优改进模型、也能带动我们以点带面的，让我们对机器学习的方法论有一个更全面更清晰的认知。这篇文章主要回顾了逻辑回归算法，并具体从数学角度去剖析算法背后的建模思路和实现逻辑。

**推荐语**：

> 逻辑回归是一种广义的线性回归分析模型，常用于数据挖掘等领域，是机器学习中，监督学习下的一种用于解决二分类问题的实用方法，用来判断事件的可能性。移动互联网时代，所有公司不断挖掘用户的潜力，推荐算法就是其中重要的基石，被广泛应用于短视频、电商等诸多领域，而逻辑回归就是推荐模块中最常见的设计，用于分析用户数据的特征……相信本文可以帮助你快速入门逻辑回归，在机器学习领域中打开一片天地。
