### ISSUE TITLE
The Clean Architecture - 整洁架构

### ISSUE THREAD

**Issue by finmily** [o2team/tech-weekly#173]
[The Clean Architecture - 整洁架构](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

[翻译版本](https://zhuanlan.zhihu.com/p/64343082)

**概要**：

> 关于整体系统架构的想法有非常多，有着相似之处。本文围绕这些系统架构的关键点展开讲解，由内及外分别是实体、用例、适配器、框架和驱动。需要遵循的规则是内层永远不能依赖于外层的数据结构或者逻辑，对于代码的易读、可扩展、可维护、可重用将有很大提升。

**推荐语**：

> 本文为 Uncle Bob 的 [`The Clean Architecture 《架构整洁之道》`](https://item.jd.com/12447192.html) 的前身。你是否可以在短时间内对所使用的 Web / RPC 或者数据库进行切换，是否在为项目整体架构、代码分层踩过的坑感到困扰，通过这篇文章来获取启发！本文只是简短的讨论了架构设计，而书中的内容可以让你从代码层面和宏观两个层面对整个软件设计有一个全面的了解。

**Comment by ZakaryCode** [comment]
[系统架构整洁的基本要素](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

**概要**：

> 关于整体系统架构的想法有非常多，有着相似之处。本文围绕这些系统架构的关键点展开讲解，由内及外分别是实体、用例、适配器、框架和驱动。需要遵循的规则是内层永远不能依赖于外层的数据结构或者逻辑，对于代码的易读、可扩展、可维护、可重用将有很大提升。[翻译版本](https://zhuanlan.zhihu.com/p/64343082)

**推荐语**：

> 本文为 Uncle Bob 的 [`The Clean Architecture 《架构整洁之道》`](https://item.jd.com/12447192.html) 的前身。你是否可以在短时间内对所使用的 Web / RPC 或者数据库进行切换，是否在为项目整体架构、代码分层踩过的坑感到困扰，通过这篇文章来获取启发！本文只是简短的讨论了架构设计，而书中的内容可以让你从代码层面和宏观两个层面对整个软件设计有一个全面的了解。
