### ISSUE TITLE
改变游戏规则的 Shell 脚本工具

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#178]
[改变游戏规则的谷歌 Shell 脚本工具](https://github.com/google/zx)

**概要**：

> Bash 很棒没错，但在编写脚本工具时，人们通常会选择一种更方便的编程语言。标准的 Node.js 库在使用之前需要许多额外的操作，例如安装依赖、引入库等。zx 提供一个 child_process 的封装，减少转义参数、返回值处理等繁琐操作。

**推荐语**：

> 这是一个对开发者更友好的编写脚本的工具，短短几天就获得破万的 Star（谷歌出品加持）。zx 工具跟以往写 Node.js 脚本最大的不同，是对 child_process 模块的封装，设计和体验都俱佳，另外还支持执行远程脚本。

**Comment by ZakaryCode** [comment]
[改变游戏规则的脚本工具](https://github.com/google/zx)

**概要**：

> Bash 很棒没错，但在编写脚本工具时，人们通常会选择一种更方便的编程语言。标准的 Node.js 库在使用之前需要许多额外的操作，例如安装依赖、引入库等。zx 提供一个 child_process 的封装，减少转义参数、返回值处理等繁琐操作。

**推荐语**：

> 这是一个对开发者更友好的编写脚本的工具，短短几天就获得破万的 Star（谷歌出品加持）。zx 工具跟以往写 Node.js 脚本最大的不同，是对 child_process 模块的封装，设计和体验都俱佳，另外还支持执行远程脚本。
