### ISSUE TITLE
轻量级 Postman 替代工具 —— Thunder Client

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#179]
[轻量级 Postman 替代工具 —— Thunder Client](https://www.thunderclient.io/)

**概要**：

> 轻量级 Rest Client，提供 VS Code 插件的 Postman 替代工具

**推荐语**：
> Postman 毕竟是付费软件，日常的业务开发场景下，开发者往往只需要轻量的测试 API 的工具，Thunder Client for VSCode 也许是更好的选择。

**Comment by ZakaryCode** [comment]
[轻量级 Postman 工具](https://www.thunderclient.io/)

**概要**：

> Postman 替代工具，轻量级 Rest Client，目前在 VSCode 插件市场中有接近 16w 下载量，入股不亏！

**推荐语**：
> Postman 毕竟是付费软件，日常的业务开发场景下，开发者往往只需要轻量的测试 API 的工具，Thunder Client for VSCode 也许是更好的选择。
