### ISSUE TITLE
支付宝 App 3D 动画和小游戏背后的故事

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#18]
链接：https://mp.weixin.qq.com/s/UOFEc4w4rRAQXtIVEm444Q

文中介绍了支付宝业务线从 17 年推出 AR 红包开始，在 Web3D 上的尝试。通过从0开发 R3 渲染引擎、下至由浏览器层面针对 Web3D 进行兼容等等努力，诞生了「星星球」等营销方案成功的 Web3D 游戏。在此过程中，团队也在“技术落地，业务探索，降低成本”方面做了不少尝试。文末分析了 Web3D 的短板所在，并结合技术趋势推测出未来的发展前景，值得思考。

**Comment by ZakaryCode** [comment]
感谢贡献
