### ISSUE TITLE
GitHub 团队如何大规模运用 Web Components？

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#182]
[GitHub 团队如何大规模运用 Web Components？](https://github.blog/2021-05-04-how-we-use-web-components-at-github/)

**概要**：

> 本文讲述 Github 团队大量使用 Web Components 的实践与总结，并以「Github Elements」的名义开源更多通用的 Web Components。

**推荐语**：

> Web Compoents 技术是由 Google 推动的浏览器原生组件，已发布将近四年的时间，一直处于不温不火的状态。在 Github 大规模使用 Web Components，并且开源自家的 Github Elements 组件之后，Web Components 能否有所起色呢，敬请期待吧~

**Comment by ZakaryCode** [comment]
[GitHub 团队的跨框架组件](https://github.blog/2021-05-04-how-we-use-web-components-at-github/)

**概要**：

> 为什么完全移除了 jQuery 并转向 Web Components？怎么高效书写健壮、无依赖、高质量的 Web Components？ViewComponent 、Catalyst 真的好用么？这篇基于 GitHub 团队开发 Web Components 并大量实践使用的总结文章会给你答案，同时 GitHub 团队将以「Github Elements」的名义开源更多通用的 Web Components。

**推荐语**：

> Web Compoents 技术是由 Google 推动的浏览器原生组件，已发布将近四年的时间，一直处于不温不火的状态。在 GitHub 大规模使用 Web Components，并且开源自家的 GitHub Elements 组件之后，Web Components 能否有所起色呢，敬请期待吧~
