### ISSUE TITLE
Google 出品的 CSS 课程

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#183]
[Google 出品的 CSS 课程](https://web.dev/learn/css/)

**概要**：

> 本课程将系统地介绍 CSS 基础，适用于初学者和高阶开发人员，通过学习课程的各个模块，您将会了解 CSS 的核心概念，并且知道如何在项目中有效地运用。

**推荐语**：

> Google 出品必属精品，CSS 作为前端最基础的技能，跟着 Una Kravets 大神重新学习 CSS，大概率会有新的收获。另外，安利 Una Kravets 大神的播客「The CSS Podcast」

**Comment by ZakaryCode** [comment]
[Google 出品的 CSS 课程](https://web.dev/learn/css/)

**概要**：

> 本课程将系统地介绍 CSS 基础，适用于初学者和高阶开发人员，通过学习课程的各个模块，您将会了解 CSS 的核心概念，并且知道如何在项目中有效地运用。

**推荐语**：

> Google 出品必属精品，CSS 作为前端最基础的技能，跟着 Una Kravets 大神重新学习 CSS，大概率会有新的收获。另外，安利 Una Kravets 大神的播客「The CSS Podcast」
