### ISSUE TITLE
神器！在浏览器中运行 Node.js

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#184]
[神器！在浏览器中运行 Node.js](https://blog.stackblitz.com/posts/introducing-webcontainers/)

**概要**：

> 几年前，我们意识到网络正朝着一个关键的拐点发展。WebAssembly 的出现让我们可以有能力编写基于 WebAssembly 的操作系统，这个操作系统的功能强大到可以完全在浏览器中运行 Node.js。我们设计了一个比本地环境更快，更安全和一致的高级开发环境，可以实现无缝代码协作，而不需要设置本地环境。两年后的今天，他终于诞生了！

**推荐语**：

> 在最近的 Google I/O 主题演讲中，Stackblitz 向大家介绍了他们与 Next.js 和 Google 团队合作开发的 IDE WebContainers，给 CloudIDE 带来了革命性的变化，非常惊艳！

**Comment by ZakaryCode** [comment]
把 Node.js 搬进浏览器
