### ISSUE TITLE
当原生云游戏遇上互动直播

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#19]
链接：https://mp.weixin.qq.com/s/RxXF7z6pophKrJBRhGmIug

7月22日的云鹭科技云游戏互动直播分享会上，云鹭科技 CEO 温向东在直播中为大家分析了目前游戏开发者们遇到的困境，并针对这些困境提出了“入局云游戏”的解决方法。从轻量级游戏入手，并成立委员会，以对原生云游戏进行多方位的支持。

**Comment by ZakaryCode** [comment]
感谢贡献
