### ISSUE TITLE
在 React 内使用内联函数的性能损耗究竟有多少？

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#21]
链接：https://www.matthewgerstman.com/tech/performance-testing-anonymous-functions/

一直有人教导我们：在 React 里用形如 “onClick={() => { /* xxx */ }}” 函数内联的写法会降低性能，是不好的。但你想过具体有多大影响吗？Matthew Gerstman 想知道影响的具体程度，所以他做了验证。结果发现，尽管内联函数存在着性能损耗，但这种损耗近乎可以忽略不计。

**Comment by ZakaryCode** [comment]
感谢贡献
