### ISSUE TITLE
【基础技术】浏览器的任务、微任务、队列和调度

### ISSUE THREAD

**Issue by Pines-Cheng** [o2team/tech-weekly#22]
浏览器里的事件循环（Event Loop）一直都是一个老生常谈的话题，社区里各种文章和资料也不少，但是你真的清楚事件循环里面的 tasks、microtasks、queues 这些概念以及他们的调度关系吗？本文是 Google Chrome 的开发人员 Jake Archibald 撰写的一篇博客，内容深入浅出，在任务调度及 JS 栈的部分还细心的绘制了 CSS 交互动画，最后还探讨了不同浏览器的差异以及相关规范的定义，非常值得一读。

地址：https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by ZakaryCode** [comment]
感谢贡献
