### ISSUE TITLE
[工具推荐] PloyK.js,一个处理多边形的js工具库

### ISSUE THREAD

**Issue by eijil** [o2team/tech-weekly#23]
[PloyK.js](http://polyk.ivank.net/?p=documentation) 提供了多个函数来帮助你更轻松的处理多边形，搭配一些物理引擎也可以做出一些有趣的效果，例如下面这个使用phaser+matter.js的[demo](https://www.emanueleferonato.com/2019/03/15/slicing-splitting-and-cutting-html5-physics-bodies-using-phaser-matter-js-and-polyk/)，基于ployk.js库可以用很少的代码实现物体的切片，这可能可以给你开发H5游戏带来一些新的想法

**Comment by ZakaryCode** [comment]
感谢贡献
