### ISSUE TITLE
【基础技术】2020 Chrome DevTools 的新特性介绍

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#25]
链接：https://css-tricks.com/whats-new-in-devtools-2020/

作为前端开发，与 Chrome 打交道是家常便饭，我们有必要了解 Chrome 调试工具的更新迭代，对日常开发和调试带来哪些帮助和改善。新 Chrome DevTools 集成了 lighthouse，并且在元素审查面板和性能面板都有一定程度的优化，本文还提供了相关特性的视频演示，非常易于理解学习。

**Comment by ZakaryCode** [comment]
感谢贡献
