### ISSUE TITLE
【基础技术】Node.js 内存泄漏指南

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#26]
链接：https://www.arbazsiddiqui.me/a-practical-guide-to-memory-leaks-in-nodejs/

由于 Javascript 采取了基于垃圾回收机制的内存管理方式，所以开发人员一般不会关注内存的分配和释放，但在开发过程中稍不注意就可能造成严重的内存泄漏。本文解释了 Javascript 的垃圾回收机制，列举实际例子介绍 Node 服务中的内存泄漏场景，并且重点讲述了如何利用 heapdump 和 chrome devtools 来精准定位线上服务的内存泄漏位置，对于 Node 服务的性能优化有参考意义。

**Comment by ZakaryCode** [comment]
感谢贡献
