### ISSUE TITLE
【图形编程】使用web worker驱动webGL渲染

### ISSUE THREAD

**Issue by wenxiongid** [o2team/tech-weekly#27]
https://evilmartians.com/chronicles/faster-webgl-three-js-3d-graphics-with-offscreencanvas-and-web-workers

介绍透过OffscreenCanvas API，实现web worker驱动webGL渲染。把更新渲染的逻辑分到主线程之外能有效减少js执行导致的页面响应阻塞。文中提供了一个demo的对比数据。

**Comment by ZakaryCode** [comment]
感谢贡献
