### ISSUE TITLE
【前端框架】Algebraic Effects for the Rest of Us

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#29]
https://overreacted.io/algebraic-effects-for-the-rest-of-us/

React team 的 Sebastian（曾提出 Hooks 与 Suspense 等特性） 常常谈到 React 的某些特性其实是以 Algebraic Effects 作为心智模型，这让他的同事 Dan （Redux 作者）非常好奇。一番探索之后 Dan 发现这个从函数式编程领域而来的概念并没有一些学术论文上写的那么复杂，因此透过本文向不了解 Algebraic Effects 的开发者进行科普，并讲述了它与一些 React 特性之间的抽象联系。

**Comment by ZakaryCode** [comment]
感谢贡献
