### ISSUE TITLE
【服务端安全】 Node.js Legacy url API 的安全风险 

### ISSUE THREAD

**Issue by booxood** [o2team/tech-weekly#3]
链接：https://zhuanlan.zhihu.com/p/102338473

在 Node.js v11.0.0 的版本中Legacy URL API已被弃用转而使用WHATWG API，但V11以下的版本中还会存在相关漏洞，由于兼容问题，Node.js 并未直接移除 legacy API。两套 API 尽管看起来提供一样的能力，但是底层对 url 规范的定义不一样，且实现也略有不同，legacy API 中隐藏了一些严重的安全风险。

via. 勇哥

**Comment by ZakaryCode** [comment]
感谢贡献
