### ISSUE TITLE
【前端框架】Recoil: State Management for Today's React

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#31]
https://www.youtube.com/watch?v=_ISAA_Jt9kI&list=PLCC436JpVnK0Q4WHoB85ZYBwcCyTaMgAl

在 5 月的 React Europe 2020 上，Dave McCabe 为我们分享了 FaceBook 推出的状态管理工具 Recoil。在状态管理工具琳琅满目的今日，为什么 React 官方要躬身入局？Recoil 的诞生是为了解决什么问题？Recoil 又如何是如何兼容 React 最新的特性呢？详情请看视频回顾。

**Comment by ZakaryCode** [comment]
感谢贡献
