### ISSUE TITLE
【前端框架】深入React fiber架构及源码

### ISSUE THREAD

**Issue by xuanzebin** [o2team/tech-weekly#34]
https://zhuanlan.zhihu.com/p/57346388
在React框架中，总是有一个用于保持状态的内部实例树(internal instances)（组件，DOM节点等），与之相对的是跟具体平台有关的public instance，也被称为Host instance 。从React 16开始，React推出了该内部实例树的新实现以及负责操作树的算法，被称为Fiber，它能够将任务分片，划分优先级，同时能够实现类似于操作系统中对线程的抢占式调度，功能非常强大。有兴趣的小伙伴可以通过这篇文章进行深入的了解~

**Comment by ZakaryCode** [comment]
感谢贡献
