### ISSUE TITLE
【工具推介】Postwoman - 一个开源、免费、快速、漂亮的女邮差？

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#35]
Postman（邮差）你肯定听说过，那 Postwoman（女邮差） 呢？不满足于 Postman 的收费，又受不了 cURL 等工具的繁琐用法，Liyas Thomas 决定用 node + Vue 自己造一个轮子，这便是 Postwoman 的由来。Postwoman 是一款开源的请求构造器，支持调试 Restful 接口，WebSocket、GraphQL 等也不在话下，用法与 Postman 没有太大区别，最重要的是免费，永久的免费。
 
链接：https://github.com/hoppscotch/hoppscotch

**Comment by ZakaryCode** [comment]
感谢贡献
