### ISSUE TITLE
【设计哲学】除了 Todo App 之外，我们如何才能获得实践技术的新点子？

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#36]
学习新技术的时候，你会拿什么项目来练手呢？大部分人都会选择写一个 Todo App（提醒事项程序） 吧。作为过来人，GaneshMani 认为，Todo App、聊天室等简单的小项目固然可以让初学者熟悉语言、框架的运作，但对于职业生涯，甚至是激烈的面试竞争来说，都是远远不够的。如何想到一个更合适、更有实践意义的项目？这篇文章手把手进行了教学。
 
链接：https://dev.to/ganeshmani/how-to-find-project-ideas-to-practice-web-development-not-a-todo-app-2b0m

**Comment by ZakaryCode** [comment]
感谢贡献
