### ISSUE TITLE
【基础技术】深色模式适配指南

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#37]
地址：https://juejin.im/post/6861725116938747917
自从 iOS13 自带支持深色模式（dark mode）以来，就一直为大家所关注，仿佛支持深色模式已经成为现代移动应用和网站的一个潮流，这不得不证明 iOS 的影响力之强大。本文就 Web、APP、Flutter 如何来实现深色模式适配，进行了深入地剖析。其中 Web 适配最终采用的是 CSS 变量+降级的方案，而 iOS、Android 原生以及 Flutter 都有各自系统提供的 API 能够比较容易地实现深色模式适配。

**Comment by ZakaryCode** [comment]
感谢贡献
