### ISSUE TITLE
【工具推荐】react-spring，一个API更全面的物理引擎驱动曲线的动画框架

### ISSUE THREAD

**Issue by wenxiongid** [o2team/tech-weekly#38]
[https://www.react-spring.io/](https://www.react-spring.io/)

一个使用物理引擎（弹簧/缓震器）计算动画曲线的动画框架。比起react-motion，提供了更多的动画曲线配置项；在使用上，支持hooks和组件的方式调用，方便驱动不同的渲染方式。

**Comment by ZakaryCode** [comment]
感谢贡献
