### ISSUE TITLE
【基础技术】深入解析CSS样式表中line-height和vertical-align对渲染结果的含义

### ISSUE THREAD

**Issue by wenxiongid** [o2team/tech-weekly#39]
[https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align)

介绍了字符在渲染结果中所占区域的决定因素，对多字符组合的行的高度，和字符在行中的垂直方向对齐作了深入解析

**Comment by ZakaryCode** [comment]
感谢贡献
