### ISSUE TITLE
【工具推荐】构建在 DevOps、CI/CD 之上的研发效能度量工具

### ISSUE THREAD

**Issue by lillian98** [o2team/tech-weekly#4]
链接：https://github.com/FieldTech/xdocs/
这款工具处理的是人机协作时代，如何进行研发管理。通过标准化开发流程、CI/CD集成来实现。结合本身的业务线，在此基础上扩展开，我们可以考虑通过CI实现团队协作、前端自动化工作流，完成本地的构建部署发布测试等工作。

**Comment by ZakaryCode** [comment]
感谢贡献
