### ISSUE TITLE
【桌面开发】多语言 Cloud & Desktop IDE 的架构设计

### ISSUE THREAD

**Issue by Pines-Cheng** [o2team/tech-weekly#40]
Eclipse Theia 是一个可以利用最先进的 Web 技术开发多语言的 Cloud & Desktop IDE 的可扩展的平台。使用 Theia，你可以从源码开始开发一个 IDE，然后在浏览器或者以本地桌面应用程序的方式运行。如今 Cloud IDE 的概念大行其道，想了解业内先驱 Theia 的架构设计和技术选型吗？来看看官方的架构设计文档吧。

[Multi-Language IDE Implemented in JS - Scope and Architecture](https://docs.google.com/document/d/1aodR1LJEF_zu7xBis2MjpHRyv7JKJzW7EWI9XRYCt48)

**Comment by ZakaryCode** [comment]
感谢贡献
