### ISSUE TITLE
【基础技术】不用 Javascript！基于 CSS Space Toggle + HTML 打造一个扫雷游戏

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#41]
Space Toggle 是 CSS 变量的一种 trick 用法。使用复选框作为数据来源，通过一定的 CSS 变量组合，Space Toggle 使 CSS 具备了基础的逻辑控制能力。这个仓库仅使用 CSS + HTML 实现一个扫雷游戏，ReadME 文档中也介绍了 Space Toggle 的用法以及社区的讨论。从仓库中可以看到，除了扫雷游戏，这个技巧还有其他用法。比如，有人打造了一个 7 段数码管 Orz...。

链接: https://github.com/propjockey/css-sweeper

**Comment by ZakaryCode** [comment]
感谢贡献
