### ISSUE TITLE
【图形编程】基于虚幻4引擎打造的国产游戏《黑神话: 悟空》刷爆全网

### ISSUE THREAD

**Issue by fff-99** [o2team/tech-weekly#42]
链接 https://mp.weixin.qq.com/s/QO8WNwB7qnvTPzc6-c3EcQ

最近, 使用虚幻4游戏引擎打造的国产游戏《黑神话: 悟空》的游戏试玩视频刷爆全网, 甚至在YouTube也是反响热烈, 游戏从画质、特效、动画等多方面都属于高水准, 网友看得热血澎湃, 惊叹: 这将是第一款国产3A大作

**Comment by ZakaryCode** [comment]
感谢贡献

**Comment by ZakaryCode** [comment]
感谢贡献
