### ISSUE TITLE
【基础技术】[官宣] TypeScript 4.0 正式发布

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#43]
地址：https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/
TypeScript 4.0 正式发布啦！官方团队在这一版本中加入了如可变参数元组类型、构造函数的类属性推断、短路分配运算符、自定义 JSX Factories 等多项激动人心的特性，同时官方站点也进行了重写，看上去更加清爽。在 Stackoverflow 的开发者报告中，TypeScript 已经成为仅次于 Rust 的第二受欢迎语言，它的社区已经成熟完善，并在不断发展，拥有很多很棒的新资源可供学习，如果你之前没有使用过 TypeScript，那么现在正是上车的最佳时机。

**Comment by ZakaryCode** [comment]
感谢贡献
