### ISSUE TITLE
美国人如果把根域名服务器封了，中国将会从网络上消失？

### ISSUE THREAD

**Issue by exa-tang** [o2team/tech-weekly#44]
自从美国宣布“清洁网络”行动后，很多懂点网络的人，第一反应是，美国人会下手根域名服务器吗？这里先给出简要回答：不排除这种可能性，但并不是没有办法。一句话原因：虽然根不在我们手里，但我们有镜像。具体请看文章。
链接：https://zhuanlan.zhihu.com/p/185674120

**Comment by ZakaryCode** [comment]
感谢贡献
