### ISSUE TITLE
“亲亲抱抱举高高”？这款游戏满足你对VR的所有期待

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#46]
链接：https://mp.weixin.qq.com/s/0RXxuaTLWun5iMGVmbGRjg

虚拟现实的概念在近几年被提及的越来越频繁，但对于大众来说似乎还是一款“科幻”产品。由 Valve 公司出品的《半衰期》VR 游戏，结合 VR 设备操作上更为多样的操控设备，进行了不同于以往鼠标键盘操控游戏的交互尝试，使得游戏中的角色动作更为接近真实世界，也产生了更多的可能性，具体体验可参阅文章。

**Comment by ZakaryCode** [comment]
感谢贡献
