### ISSUE TITLE
3D特效师可以下班了丨Science

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#47]
链接：https://mp.weixin.qq.com/s/AE02UqOgDivifJpYGfI1zA

还记得“抢钱大楼” SM 娱乐公司门口的电子屏海浪吗？一看就很贵。但 DeepMind 和斯坦福等一众科学家研究出了一款图网络模拟器——GNS 框架，转变思路，由当前市场上普遍使用的通过物理规律进行 CG 计算，转向机器学习以实现物理模拟器的方案。这将大大降低 CG 特效的门槛，可能将深远地影响到这一市场。

**Comment by ZakaryCode** [comment]
感谢贡献
