### ISSUE TITLE
Vue3 Compiler 优化细节

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#48]
https://zhuanlan.zhihu.com/p/150732926

Vue3 通过编译时和运行时相配合，让 diff 性能进一步得到提升。文章详细介绍了 Compiler 会对模板分析出哪些关键信息，运行时又是怎样利用这些信息对 diff 进行优化的。假如我们不编写 template 而是直接编写渲染函数，作者也在文末介绍了我们怎么样编写渲染函数能够让 diff 进入优化模式。文章整体内容非常硬核，需要花费一定时间的进行阅读，希望读者能坚持到到最后。这里姑且引用文章中的最后一句："Don't stop learning..."，共勉。

**Comment by ZakaryCode** [comment]
感谢贡献
