### ISSUE TITLE
React TypeScript Cheatsheets

### ISSUE THREAD

**Issue by hentaicracker** [o2team/tech-weekly#49]
https://react-typescript-cheatsheet.netlify.app/

使用 TypeScript 编写 React 应用的类型 Cheatsheets，也可以看做是 TypeScript + React 最佳实践。它介绍了我们在使用 React 各种特性时最佳的 TypeScript 类型写法，帮助你解答各种类型上的问题。看完这篇，妈妈再也不用担心我不会写 tsx 了。

**Comment by ZakaryCode** [comment]
感谢贡献
