### ISSUE TITLE
【前端框架】Vue 3: mid 2020 status update

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#5]
## [Vue 3: mid 2020 status update](https://github.com/vuejs/rfcs/issues/183)

近日 Vue3 团队对 Vue 3 的状态进行了更新，介绍了各个主要工具的开发进度。整体计划是 7 月中旬推出 RC 版本，8 月早些时候能够推出正式版。在各工具在密锣紧鼓升级兼容 Vue3 的同时，受 [Svelte](https://svelte.dev/tutorial) 启发，尤大新增了[三个语法糖特性](https://github.com/vuejs/rfcs/pull/182)用于优化 SFC 的开发体验，一起来了解一下吧～。

**Comment by ZakaryCode** [comment]
感谢贡献，本期推荐！
