### ISSUE TITLE
【基础技术】Lodash 安全漏洞背后，你不得不知道的 JavaScript 知识

### ISSUE THREAD

**Issue by AwesomeDevin** [o2team/tech-weekly#50]
链接：https://zhuanlan.zhihu.com/p/73186974

该篇文章内容可以加深读者对JavaScript基础知识的理解，通过对`Loadsh`潜在安全漏洞及其修复方案的分析，可以帮助读者对原型污染的产生、原型污染攻击方式及相关防范措施进行深入了解，涉及到的知识点包括但不限于：`Object 原型`、`原型`、`原型链`、`NodeJS 相关问题`、`Object.create 方法`、`Object.freeze 方法`、`Map 数据结构`、`深拷贝`。

**Comment by ZakaryCode** [comment]
感谢贡献
