### ISSUE TITLE
【AI】算法的落地《推荐系统实践》一书推荐

### ISSUE THREAD

**Issue by kyjo2014** [o2team/tech-weekly#51]
本书主要提供了搭建推荐系统过程会遇到的数据来源，数据分类，算法/模型选择，以及效果评价等问题的思考方向。并以大量工程化的内容结合少量算法讲解，十分适合了解算法落地。豆瓣评分8.1。

https://book.douban.com/subject/10769749/

**Comment by ZakaryCode** [comment]
感谢贡献
