### ISSUE TITLE
【设计哲学】只加 2 行代码，为什么要花 2 天时间？

### ISSUE THREAD

**Issue by wengeek** [o2team/tech-weekly#52]
针对不懂技术的上司或者 PM，该如何回答这个问题？本文列出了一些可能的理由。

原文：https://www.mrlacey.com/2020/07/youve-only-added-two-lines-why-did-that.html
译文：https://zhuanlan.zhihu.com/p/162925587

**Comment by ZakaryCode** [comment]
感谢贡献
