### ISSUE TITLE
【基础技术】Text Fragments，一种你没见过的锚点技巧

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#53]
链接：https://web.dev/text-fragments/

Text Fragments（文本片段）是 Chromium 80+ 的新功能。使用 Text Fragments，我们可以在 URL 中指定文本片段作为锚点。当浏览器打开一个带有 Text Fragments 的 URL 时，浏览器会对匹配到的文本进行强调，引起用户的注意。

**Comment by ZakaryCode** [comment]
感谢贡献
