### ISSUE TITLE
【前端框架】用 React 和 Vue 做了两个完全一样的 App 之后，这是我的完整对比评测

### ISSUE THREAD

**Issue by Littly** [o2team/tech-weekly#54]
链接：https://sunilsandhu.com/posts/i-created-the-exact-same-app-in-react-and-vue-2020-edition

“对比一下 React 和 Vue” 是一道常见的面试题。Sunil Sandhu 兄弟想要更为中立地回答这个问题，所以他一直在尝试构建一个标准、完整的 Todo App 来对比这俩框架的工作流程。在 React Hooks 和 Vue Composition Api 分别发布后，他发布了 2020 版的 React & Vue 对比评测。

**Comment by ZakaryCode** [comment]
感谢贡献
