### ISSUE TITLE
【图像编程】不顾一切找圆角 —— Figma 实时平滑圆角方案探究

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#55]
链接：http://www.martinrgb.com/blog/#/Figma_Round_Corner

你还在粗暴地使用直角圆角吗？在 iOS7 时代，苹果对主屏图标做了非常精巧的改动，引入了平滑圆角的概念。使用数学语言来描述便是：平滑圆角的边缘曲率是连续的，而直角圆角不是。这看似微不足道，但这种设计小细节却有很大的体验影响。

**Comment by ZakaryCode** [comment]
感谢贡献
