### ISSUE TITLE
【基础技术】从 Web 图标演进历史看最佳实践

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#56]
链接：https://mp.weixin.qq.com/s/cM1qo3ApcA7MBbNcFm8c0A

在产品中适当使用图标，可以让产品更生动，也更简洁。在前端项目中，处理和引入图标都是必不可少的环节。本文将简单梳理一下图标相关的工作流程的演进，以及我们在百度设计语言系统推进过程中相关的一些尝试。

**Comment by ZakaryCode** [comment]
感谢贡献
