### ISSUE TITLE
【站点推荐】SVG 开发相关博客：Cassie Evans's Blog

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#6]
链接：https://www.cassie.codes/

这是一个充满了 SVG 动效小心思的个人博客，从左上角的 Logo 到首屏的空心字 hover 效果，以及最后一屏目光跟随鼠标的个人画像，这个博客首页的所有图形都是使用 SVG 绘制而成。博客中包含了关于 SVG 动效开发入门、绘制等内容，适合对 SVG 动效感兴趣的人边探索边学习。

**Comment by ZakaryCode** [comment]
感谢贡献
