### ISSUE TITLE
【基础技术】libuv 教程

### ISSUE THREAD

**Issue by Pines-Cheng** [o2team/tech-weekly#60]
[libuv User Guide](http://docs.libuv.org/en/v1.x/guide.html)

熟悉 Node 的同学，对 libuv 肯定不陌生。libuv 是一个高性能的，事件驱动的I/O库，并且提供了跨平台（如 Windows，Linux）的API。[Nikhil Marathe](http://nikhilism.com/) 在写node-taglib 的时候苦于没有好理解的 libuv 教程，于是就写了这本小册，现在已经被纳入 libuv 官方文档，有兴趣的同学，不妨尝试看一看，一定会为你打开一个新的世界。

**Comment by ZakaryCode** [comment]
感谢贡献
