### ISSUE TITLE
【基础技术】AVIF 来了

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#61]
链接：https://jakearchibald.com/2020/avif-has-landed/
译文：https://juejin.im/post/6870741995204132877

本文使用四幅不同的图片：细节丰富的照片/平面插画/重型SVG/渐变图作为 Demo，将常见的图片格式：JPEG，WebP，PNG 与 AVIF 进行比较，揭秘 Netflix 为什么选择 AVIF 作为下一代的图片压缩技术。

**Comment by ZakaryCode** [comment]
感谢贡献
