### ISSUE TITLE
快速上手 WebAssembly 应用开发：Emscripten 使用入门

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#62]
https://mp.weixin.qq.com/s/vA231eCDVNx6d7gIqMEe9g

Emscripten 是 WebAssembly 工具链里重要的组成部分。它能够帮助我们把 C/C++ 编译为 asm.js 或 WebAssembly，输出可以运行在 Web、Node.js 和 wasm runtimes 的代码。文章从一个 C 的 HelloWorld 展开，逐步介绍了调试、WASM 与 JavaScript 相互调用、Emscripten API 等知识点。阅读完本文后，读者能够掌握 Emscripten 的基本用法，学习到 asm.js/WASM 与 JavaScipt 实现交互的部分细节。

**Comment by ZakaryCode** [comment]
感谢贡献
