### ISSUE TITLE
An Introduction to Vue Teleport — A New Feature in Vue3

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#63]
https://medium.com/@mattmaribojoc/an-introduction-to-vue-teleport-a-new-feature-in-vue3-e9ddbf58dd25

Teleport 是 Vue3 的一个新特性，作用与 React Portal 类似。它能让我们把指定的模板节点渲染到特定的容器上，非常有助于实现如 Modals、Notifications 等“全局”模块。本文介绍了引入 Teleport 的背景以及其基本用法，配合 [Vue3 teleport 文档](https://v3.vuejs.org/guide/teleport.html)服用，效果更佳。

**Comment by ZakaryCode** [comment]
感谢贡献
