### ISSUE TITLE
What’s New In React Router 6

### ISSUE THREAD

**Issue by Chen-jj** [o2team/tech-weekly#64]
https://medium.com/frontend-digest/whats-new-in-react-router-6-732b06cc83e4

React Router 最近发布了 6.x 的 beta 版本，相信很快将会发布正式版。作为 React 生态的重要组成部分，React Router 被广泛用于各 React 项目中。本次的升级将会引入哪些新特性、又是否会带来非兼容性改动呢？本文详细介绍了 React Router 6 的各项具体改动，其中 Route/Link 组件需要书写相对路径、支持以对象形式定义路由以及 suspense-ready navigate API 比较值得关注。

**Comment by ZakaryCode** [comment]
感谢贡献
