### ISSUE TITLE
使用 WebGL 实验图像三角形转场效果

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#67]
https://tympanus.net/codrops/2020/08/27/experimental-triangle-image-transitions-with-webgl/

作者凭借着对三角几何图形浓厚的爱，设计了一种针对图像的三角形转场效果。基于这一想法，作者提供了5种转场效果，包含区域切割、图形翻转等。

**Comment by ZakaryCode** [comment]
感谢贡献
