### ISSUE TITLE
【前端框架】尤大发在 GitHub 上的 vue-lit 是啥？

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#69]
本文介绍了 Vue3 作者尤大在 GitHub 上发布的一个可以使用 Vue 的写法来渲染成 Web Component 的验证性库。vue-lit 借助 @vue/reactivity 和 lit-html 两个库将 vue 与 Web Component 结合到一块儿，这个想法还是非常有趣的。众所周知 Web Component 是浏览器原生的组件化能力，如果我们能用现代前端框架的 API 来进行原生组件化开发，而不需要引入前端框架和打包编译，那岂不是非常美好。vue-lit 本身非常短小精悍，建议可以通过阅读源码了解精髓。

文章地址：https://juejin.im/post/6874383765070675976

**Comment by ZakaryCode** [comment]
感谢贡献
