### ISSUE TITLE
【图形编程】如何挑选数据可视化框架及平台 - 前端篇

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#7]
链接：https://zhuanlan.zhihu.com/p/149398216

在数字化成为趋势的今天，数据可视化需求也越来越常见。这篇文章挑选了市面上较活跃较稳定的框架进行了详细的测评，包含框架的发展历史、优劣势、与其他框架存在的区别等角度，适合正在或即将挑选数据可视化框架的前端开发对这些框架进行一个全面的了解，以便选择最为适合的框架。

**Comment by ZakaryCode** [comment]
感谢贡献
