### ISSUE TITLE
Danfo.js ：深受 Pandas 启发的 JavaScript 开源库

### ISSUE THREAD

**Issue by booxood** [o2team/tech-weekly#70]
Danfo.js 是个 JavaScript 开源库，提供了高性能、直观易用的数据结构，支持结构化数据的操作和处理。Danfo.js 深受 Python Pandas 库的启发，并提供了类似的接口/API。因此熟悉 Pandas API 且了解 JavaScript 的用户可以轻松上手。

文章地址：https://mp.weixin.qq.com/s/J-f7o0FsAFC44cT-OyL7PA

**Comment by ZakaryCode** [comment]
感谢贡献
