### ISSUE TITLE
【图形编程】Airbnb 发布 Visx 1.0 正式版

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#71]
官网：https://airbnb.io/visx/
链接：https://medium.com/airbnb-engineering/introducing-visx-from-airbnb-fd6155ac4658

时隔三年，Airbnb 使用 TypeScript 重写并发布了 Visx 1.0 正式版，Visx 是一套结合 D3 开发的 React 低阶可视化原型组件。

**Comment by ZakaryCode** [comment]
感谢贡献
