### ISSUE TITLE
【基础技术】microcosmos 微前端框架的实现

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#72]
作者参考阿里 qiankun 微前端框架的设计思路，自己实现了一个微前端框架。本文对微前端的方案介绍、实现思路都提供了详细的阐述，对于微前端技术感兴趣的同学很有帮助。

文章地址：https://juejin.im/post/6864381092061773831#heading-5

**Comment by ZakaryCode** [comment]
感谢贡献
