### ISSUE TITLE
【基础技术】TC39:  proposal-decorators 装饰器提案

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#73]
TC39 对装饰器方案的研究已经有超过5年的历史，本次提出的方案与Babel基于旧提案实现的装饰器、Typescript 的试验性装饰器都有所不同，这主要是出于对引擎的可优化性考虑。

文章地址：https://github.com/tc39/proposal-decorators

**Comment by ZakaryCode** [comment]
感谢贡献
