### ISSUE TITLE
【基础技术】100 行代码重写 Recoil 状态管理库

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#74]
Recoil 是 Facebook 官方推出的一个状态管理器解决方案，更好地拥抱 hooks。本文作者用 100 行内的代码实现了一个简化版的 Recoil，其对 Recoil Atom 和 Selector 的实现都做了手把手的讲解，有利于读者更好地理解 Recoil 的个中原理。

文章链接：https://bennetthardwick.com/blog/recoil-js-clone-from-scratch-in-100-lines/

**Comment by ZakaryCode** [comment]
感谢贡献
