### ISSUE TITLE
【基础技术】为什么要使用 pnpm？

### ISSUE THREAD

**Issue by JunreyCen** [o2team/tech-weekly#75]
pmpm 是类似于 npm 和 yarn 的一个 Javascript 包管理器。作为 npm 的直接替代品，pnpm 的速度更快、效率更高，且不存在像 yarn 一样的磁盘空间占用问题，非常适合 monorepos 的仓库模式。如果你感兴趣了，一定要读读这篇 pnpm 作者写的文章：为什么要使用 pnpm？

文章链接：https://www.kochan.io/nodejs/why-should-we-use-pnpm.html

**Comment by ZakaryCode** [comment]
感谢贡献
