### ISSUE TITLE
看完这篇文章，我奶奶都懂了https的原理

### ISSUE THREAD

**Issue by exa-tang** [o2team/tech-weekly#76]
文章由浅入深展示了对称加密、非对称加密、数字证书、CA机构、数字签名等在 https 协议过程中所扮演的角色，语言通俗易懂，虽然拉着奶奶一起看，奶奶表示看不懂，但还是值得推荐！

https://www.cnblogs.com/sujing/p/10927569.html

**Comment by ZakaryCode** [comment]
感谢贡献
