### ISSUE TITLE
论文解读：基于动态词表的对话生成研究

### ISSUE THREAD

**Issue by Manjiz** [o2team/tech-weekly#77]
虽然是18年的文章，但通过本文主要可以了解聊天机器人的分类以及实现思路，至于本文的核心内容，用动态词典替换静态词典的实现思路以及优化词预测损失和回复生成损失方法，则适合更深入研究的读者。

http://blog.sina.com.cn/s/blog_4caedc7a0102x3o1.html

**Comment by ZakaryCode** [comment]
感谢贡献
