### ISSUE TITLE
京东数据科学团队关于聊天机器人的综述文章

### ISSUE THREAD

**Issue by Manjiz** [o2team/tech-weekly#78]
A Survey on Dialogue Systems: Recent Advances and New Frontiers.（智能对话系统调查：前沿与进展）

虽然也是2018年的，全文引用了124篇论文，是一篇综合全面的介绍对话系统的文章，现在看来仍具有参考意义。

https://www.kdd.org/exploration_files/19-2-Article3.pdf

**Comment by ZakaryCode** [comment]
感谢贡献
