### ISSUE TITLE
Write three.js in React Using react-three-fiber

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#79]
链接：https://www.digitalocean.com/community/tutorials/react-react-with-threejs

如何优雅地使用 React 写 three.js，本篇文章提供了入门教程。文中罗列了选择 R3F（react-three-fiber）的理由：组件化场景的开发模式可读性极高且便于复用，内置了很多相当有用的辅助函数，暴露了足够多的 hooks 以便开发者灵活扩展，提前预处理画布尺寸，不限制 three.js 的使用版本，对二次渲染的算法做了优化。

**Comment by ZakaryCode** [comment]
感谢贡献
