### ISSUE TITLE
【设计哲学】前后端一体化：前后端分离将死？

### ISSUE THREAD

**Issue by luckyadam** [o2team/tech-weekly#8]
地址：https://www.phodal.com/blog/kill-frontend-backend/

天下大势，分久必合，合久必分，在几年前由于 NodeJS 等技术的蓬勃发展，业界涌现出前后端分离的技术架构体系，仿佛前后端分离，才是自然的法则。而如今，也是因为技术的不断发展，作者基于自身敏锐的观察，开始探索前后端一体化的架构，并列举了一系列关于前后端一体化即将到来的观点，非常值得学习、思考。不过，不管是哪种架构，都是为了在合适的时机出现，解决当下的问题，架构，没有终点。

**Comment by ZakaryCode** [comment]
感谢贡献
