### ISSUE TITLE
【ARCore 开发入门课程系列】AR 核心概念及技术解析

### ISSUE THREAD

**Issue by lyxuncle** [o2team/tech-weekly#80]
链接：https://mp.weixin.qq.com/s/L-IIhrodV_fM5N4Ppt647Q

这是谷歌推出的 ARCore 开发入门课程系列中的第二节课，介绍了 AR 的六大理念，以及 ARCore 实现这六大理念的思路与技术解决方案。文章开头提到的上节课《解密 AR 增强现实》的内容也同样值得一读。

**Comment by ZakaryCode** [comment]
感谢贡献
