### ISSUE TITLE
历经十年岁月磨砺，这个网页视频播放器中的王牌终于开源了！

### ISSUE THREAD

**Issue by xuanzebin** [o2team/tech-weekly#81]
ckplayer 是一款用于网页上播放视频的软件，它有着高度自定义化的特点；而且作为一个老牌的网页视频播放器，使用起来只需几个简单的文件即可插入视频。而在最近，该播放器作者在更新了 X2 版本后，又将 ckplayer 正式开源给各位开发者，本文将带大家简单介绍该播放器的特点以及使用和安装方式。

https://zhuanlan.zhihu.com/p/257096128

**Comment by ZakaryCode** [comment]
感谢贡献
