### ISSUE TITLE
阔别两年，webpack 5 正式发布

### ISSUE THREAD

**Issue by Pines-Cheng** [o2team/tech-weekly#82]
自从 2018 年 2 月，Webpack 4 发布以来，Webpack 就暂时没有更进一步的重大更新，为了保持 API 的一致性，旧的架构没有做太多改变，遗留了很多的包袱。阔别 2 年多后，2020 年 10 月 10 日，Webpack 5 正式发布，并带来了诸多重大的变更，将会使前端工程师的构建效率与质量大为提升。Webpack 5 的 Release Note 非常长，本文尝试摘出最简练的信息。

https://mp.weixin.qq.com/s/sh7rcv6hdhYfWr1bv_ssbg

**Comment by ZakaryCode** [comment]
感谢贡献
