### ISSUE TITLE
svga——AE动画的另一个实现/展示方法

### ISSUE THREAD

**Issue by wenxiongid** [o2team/tech-weekly#84]
官网: [https://svga.io/](https://svga.io/)

相比起有名的bodymovin lottie，svga使用了另一种方法记录动画信息：每一帧的信息在导出前计算好，记录在导出好的文件中，播放器在渲染时只需逐帧渲染，不需关心关键帧间插值的计算。由此带来的是解析、播放器的库比lottie的精简许多(gzip前57KB)，导出的文件也较小；另外限制也更多：不支持复杂的矢量形状图层、不支持AE自带的渐变、生成、描边、擦除等、对设计工具原生动画不友好，对图片动画友好

**Comment by ZakaryCode** [comment]
感谢贡献
