### ISSUE TITLE
NPM v7.0.0 发布

### ISSUE THREAD

**Issue by wengeek** [o2team/tech-weekly#85]
https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

npm v7.0.0 带来了比较多的新特性，Workspaces、peerDependencies 自动被安装、支持 yarn.lock 等，将与 NodeJS v15 一起发布。如果你想立即尝试，可以使用 npm i -g npm@7 在终端运行安装。

**Comment by ZakaryCode** [comment]
感谢贡献
