### ISSUE TITLE
Chrome 正在启用 HTTP/3，支持 IETF QUIC

### ISSUE THREAD

**Issue by wengeek** [o2team/tech-weekly#86]
原文：https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html
译文：https://www.oschina.net/news/119045/chrome-is-deploying-http3-and-ietf-quic

QUIC（Quick UDP Internet Connections）是谷歌制定的一种基于UDP的低延时的互联网传输层协议，结合了TCP、TLS等协议的特性。HTTP/3 是HTTP的最新版本，仅在QUIC上运行。

**Comment by ZakaryCode** [comment]
感谢贡献
