### ISSUE TITLE
iOS UIScrollView 动画的力学原理

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#88]
原文：https://medium.com/@esskeetit/how-uiscrollview-works-e418adc47060#8fc0
译文：http://www.martinrgb.com/blog/index.html#/HOW_UIScrollView_Works

了解动画效果的力学原理对于设计的还原度非常重要，本文深度剖析 iOS UI 滚动视图动画的力学原理

**Comment by ZakaryCode** [comment]
感谢贡献
