### ISSUE TITLE
【服务端开发】错误码如何设计才合理？

### ISSUE THREAD

**Issue by Pines-Cheng** [o2team/tech-weekly#9]
对于错误码的设计，不同的开发团队有不同的风格习惯。而优秀的错误码设计，不仅能够帮助快速定位问题，让代码结构更清晰，还能间接地反映了整个架构的设计和划分。本文分享阿里文娱技术专家长统对于错误码的看法，希望从错误码使用的不同场景讨论得到一个合理的错误码规约，得到一个面向日志错误码标准和一个面向外部传递的错误码标准。

地址：https://zhuanlan.zhihu.com/p/152115647

**Comment by ZakaryCode** [comment]
感谢贡献
