### ISSUE TITLE
在项目中实践 CLS 性能指标优化

### ISSUE THREAD

**Issue by koppthe** [o2team/tech-weekly#97]
链接：https://nicj.net/cumulative-layout-shift-in-practice/?ref=ewebdesign.com

你是否试过在开始阅读一篇有趣的新闻文章時，因为所有文字突然向下移动而令你要重新找回刚才看到的部分？Chorme 83 中新增了 Cumulative Layout Shift（CLS) 指标来衡量页面「累计版面配置转移」的数值，本文将在项目中实践 CLS 指标的优化。

**Comment by ZakaryCode** [comment]
感谢贡献
