### ISSUE TITLE
TiDB一款同时支持在线事务处理与在线分析处理的融合型分布式数据库产品

### ISSUE THREAD

**Issue by zhonghuiping** [o2team/tech-weekly#98]
链接： https://docs.pingcap.com/zh/tidb/stable/tidb-architecture

内容：TiDB 是 PingCAP 公司自主设计、研发的开源分布式关系型数据库，是一款同时支持在线事务处理与在线分析处理 (Hybrid Transactional and Analytical Processing, HTAP）的融合型分布式数据库产品，具备水平扩容或者缩容、金融级高可用、实时 HTAP、云原生的分布式数据库、兼容 MySQL 5.7 协议和 MySQL 生态等重要特性。目标是为用户提供一站式 OLTP (Online Transactional Processing)、OLAP (Online Analytical Processing)、HTAP 解决方案。TiDB 适合高可用、强一致要求较高、数据规模较大等各种应用场景

**Comment by ZakaryCode** [comment]
感谢贡献
