### ISSUE TITLE
Framer Motion：让动画创建更加简单

### ISSUE THREAD

**Issue by Lanchouchou** [o2team/tech-weekly#99]
链接：https://www.smashingmagazine.com/2020/10/introduction-to-framer-motion/
内容：framer-motion是适用于react的动效库，通过将动作添加到HTML和SVG元素前面来创建动画组件，无需成为CSS专家即可创建精美的动画。本文介绍了其基本的使用方式。

**Comment by ZakaryCode** [comment]
感谢贡献
